const _default = {
    df_popup_enable: false,
    df_popup_trigger_type: 'on_load',
    df_popup_scroll_element_viewport: 'on_bottom',
    df_popup_manual_trigger: '',
    df_popup_custom_selector:'',
    df_popup_time_delay: 0,
    df_popup_scrolling_offset: '',
    df_popup_inactivity_time_delay: '',
    df_popup_activity:'always',
    df_popup_schedule_type: 'always',
    df_popup_recuring_schedule_day:'',
    df_popup_schedule_start_date: '',
    df_popup_schedule_end_date: '',
    df_popup_close_link_selector: '',
    df_popup_remove_link: false,
    df_popup_prevent_scroll: false,
    df_popup_content_scroll: false,

    df_popup_clickable_outside_popup_area: false,
    df_popup_close_on_overlay_click: false,
    df_popup_close_by_click_back_btn: false,

    df_popup_display_user_devices: ['all' , 'desktop', 'tablet', 'mobile'],
    df_popup_display_user_roles: ['all'],

    df_popup_content_position: 'center',
    df_popup_animation_type:'fade_in',
    df_popup_animation_duration: '500',
    df_popup_animation_delay: '200',
    df_popup_animation_time_function: 'linear',

    df_popup_close_animation_enable: false,
    df_popup_close_animation_type:'fade_in',
    df_popup_close_animation_duration: '100',
    df_popup_close_animation_time_function: 'linear',

    df_popup_close_btn_design_on: false,
    df_popup_overlay_bg_color: '',
    df_popup_overlay_bg_gradient: '',
    df_popup_close_btn_color: '',
    df_popup_close_btn_font_size: '48',
	df_popup_close_btn_font_weight: '600',
    df_popup_close_btn_line_height:'24',
    df_popup_close_position_type:'top_right',
    df_popup_close_position_type_for_inside:'top_right',
    df_popup_close_btn_move_inner_content: false,
    df_popup_close_btn_background: '',
    df_popup_close_btn_padding:'',
    df_popup_close_btn_margin: '',
    df_popup_close_btn_border:'',
    df_popup_close_btn_border_radius:'',

    df_popup_activity_type : 'never',
    df_popup_activity_period_type : 'day',
    df_popup_activity_period_value: '1',
    df_popup_display_condition: [{condition_type: "include", show_popup_at: "entire_site"}]
}
export default _default;
