const convertIcon = ( value ) => {
	value = value.split("|");
	value = {
		unicode:value[0],
		type:value[2],
		weight:value[4],
	}
	return value
}
const convertSpacing = ( value ) => {
	value = value.split("|");
	value = {
		top:value[0],
		right:value[1],
		bottom:value[2],
		left:value[3],
		syncHorizontal:value[4],
		syncVertical:value[5],
	}
	return value
}

export const conversionOutline = {
	advanced: {
		admin_label: "module.meta.adminLabel",
		animation: "module.decoration.animation",
		background: "module.decoration.background",
		disabled_on: "module.decoration.disabledOn",
		module: "module.advanced.htmlAttributes",
		overflow: "module.decoration.overflow",
		position_fields: "module.decoration.position",
		scroll: "module.decoration.scroll",
		sticky: "module.decoration.sticky",
		text: "module.advanced.text",
		transform: "module.decoration.transform",
		transition: "module.decoration.transition",
		z_index: "module.decoration.zIndex",
		max_width: "module.decoration.sizing",
		height: "module.decoration.sizing",
		link_options: "module.advanced.link",
		margin_padding: "module.decoration.spacing",
		fonts: {
			button_text: "text.decoration.font",
			button_sub_text: "sub_text.decoration.font",
			tooltip_text_body: "design_tooltip_text_body.decoration.font",
			tooltip_text_a: "design_tooltip_text_a.decoration.font",
			tooltip_text_ul: "design_tooltip_text_ul.decoration.font",
			tooltip_text_ol: "design_tooltip_text_ol.decoration.font",
			tooltip_text_quote: "design_tooltip_text_quota.decoration.font",
			tooltip_text_h1: "design_tooltip_header_h1.decoration.font",
			tooltip_text_h2: "design_tooltip_header_h2.decoration.font",
			tooltip_text_h3: "design_tooltip_header_h3.decoration.font",
			tooltip_text_h4: "design_tooltip_header_h4.decoration.font",
			tooltip_text_h5: "design_tooltip_header_h5.decoration.font",
			tooltip_text_h6: "design_tooltip_header_h6.decoration.font",
		},
		text_shadow: {
			default: "module.advanced.text.textShadow"
		},
		box_shadow: {
			default: "module.decoration.boxShadow",
			media: "design_media.decoration.boxShadow",
			tooltips_box_shadow:"design_tooltip.decoration.boxShadow",
		},
		borders: {
			default: "module.decoration.border",
			media: "design_media.decoration.border",
			tooltips_border:"design_tooltip.decoration.border",
		},
		filters: {
			default: "module.decoration.filters",
		}
	},
	css: {
		after:         'css.*.after',
		before:        'css.*.before',
		main_element:  'css.*.mainElement',
		text:          'css.*.text',
		sub_text:      'css.*.sub_text',
		media:         'css.*.media_container'
	},
	module: {
		button_text: "button_text.innerContent.*",
		button_sub_text: "button_sub_text.innerContent.*",
		button_icon: "button_icon.innerContent.*",
		button_image: "button_image.innerContent.*",
		button_link_type: "button_link.innerContent.*.button_link_type",
		button_link_url: "button_link.innerContent.*.button_link_url",
		button_link_download: "button_link.innerContent.*.button_link_download",
		button_link_email: "button_link.innerContent.*.button_link_email",
		button_link_phone: "button_link.innerContent.*.button_link_phone",
		button_url_new_window: "button_link.innerContent.*.button_url_new_window",
		media_placement: "media_placement.decoration.*",
		sub_text_placement: "sub_text_placement.innerContent.*",
		icon_color: "design_media.decoration.icon_color.*",
		button_icon_size: "design_media.decoration.button_icon_size.*",
		media_background_color: "design_media.decoration.media_background_color.*",
		button_alignment: "alignment.decoration.button_alignment.*",
		button_content_alignment: "alignment.decoration.button_content_alignment.*",
		media_wrapper_width: "design_media.decoration.media_wrapper_width.*",
		media_wrapper_height: "design_media.decoration.media_wrapper_height.*",
		two_d_hover_effects: "two_d_hover_effects.innerContent.*",
		two_d_transition_duration: "buttonAnimationTransition.decoration.*.two_d_transition_duration",
		two_d_transition_delay: "buttonAnimationTransition.decoration.*.two_d_transition_delay",
		bg_hover_effects: "bg_hover_effects.innerContent.*",
		bg_hover_effect_directions: "bg_hover_effect_directions.innerContent.*",
		bg_hover_skew_effect_directions: "bg_hover_skew_effect_directions.innerContent.*",
		bg_hover_effect_hyper: "bg_hover_effect_hyper.innerContent.*",
		bg_hover_hypen_color: "bg_hover_hypen_color.decoration.*",
		bg_hover_effect_bounce: "bg_hover_effect_bounce.innerContent.*",
		bg_hover_background_color: "bg_hover_background_color.decoration.*",
		bg_hover_background_secondary_color: "bg_hover_background_secondary_color.decoration.*",
		bg_transition_duration: "buttonAnimationTransition.decoration.*.bg_transition_duration",
		bg_transition_delay: "buttonAnimationTransition.decoration.*.bg_transition_delay",
		bg_transition_timing_function: "buttonAnimationTransition.decoration.*.bg_transition_timing_function",
		border_hover_effects: "border_hover_effects.innerContent.*",
		border_hover_color: "border_hover_color.decoration.*",
		stroke_transition_duration: "buttonAnimationTransition.decoration.*.stroke_transition_duration",
		stroke_transition_delay: "buttonAnimationTransition.decoration.*.stroke_transition_delay",
		stroke_transition_timing_function: "buttonAnimationTransition.decoration.*.stroke_transition_timing_function",
		media_hover_effects: "media_hover_effects.innerContent.*",
		media_hover_effect_directions: "media_hover_effect_directions.innerContent.*",
		media_transition_duration: "buttonAnimationTransition.decoration.*.media_transition_duration",
		media_transition_delay: "buttonAnimationTransition.decoration.*.media_transition_delay",
		media_transition_timing_function: "buttonAnimationTransition.decoration.*.media_transition_timing_function",
		image_icon_custom_margin: "design_media.decoration.spacing.*.margin",
		image_icon_custom_padding: "design_media.decoration.spacing.*.padding",
		use_button_icon: "use_button_icon.innerContent.*",

		field_tooltip_enable: "main_tooltip.innerContent.*.field_tooltip_enable",
		field_tooltip_content: "main_tooltip.innerContent.*.field_tooltip_content",
		field_tooltip_disable_on_mobile: "main_tooltip_settings.innerContent.*.field_tooltip_disable_on_mobile",
		field_tooltip_arrow: "main_tooltip_settings.innerContent.*.field_tooltip_arrow",
		field_tooltip_placement: "main_tooltip_settings.innerContent.*.field_tooltip_placement",
		field_tooltip_animation: "main_tooltip_settings.innerContent.*.field_tooltip_animation",
		field_tooltip_interactive: "main_tooltip_settings.innerContent.*.field_tooltip_interactive",
		field_tooltip_interactive_border: "main_tooltip_settings.innerContent.*.field_tooltip_interactive_border",
		field_tooltip_content_delay: "main_tooltip_settings.innerContent.*.field_tooltip_content_delay",
		field_tooltip_interactive_debounce: "main_tooltip_settings.innerContent.*.field_tooltip_interactive_debounce",
		field_tooltip_custom_maxwidth: "main_tooltip_settings.innerContent.*.field_tooltip_custom_maxwidth",
		field_tooltip_offset_enable: "main_tooltip_settings.innerContent.*.field_tooltip_offset_enable",
		field_tooltip_offset_skidding: "main_tooltip_settings.innerContent.*.field_tooltip_offset_skidding",
		field_tooltip_offset_distance: "main_tooltip_settings.innerContent.*.field_tooltip_offset_distance",
		field_tooltip_arrow_color: "design_tooltip.decoration.field_tooltip_arrow_color.*",
		field_tooltip_background_bgcolor: "main_tooltip.innerContent.*.color",
		field_tooltip_background_use_gradient: "main_tooltip.innerContent.*.gradient.enabled",
		field_tooltip_background_color_gradient_1: "",
		field_tooltip_background_color_gradient_2: "",
		field_tooltip_background_gradient_type: "",
		field_tooltip_background_radial_direction: "",
		field_tooltip_background_gradient_direction: "",
		field_tooltip_background_start_position: "",
		field_tooltip_background_end_position: "",
	},
	valueExpansionFunctionMap: {
		button_icon: convertIcon,
		image_icon_custom_margin: convertSpacing,
		image_icon_custom_padding: convertSpacing
	}
}