const convertInlineValue = (value) => {
  return _.isString(value) ? value.split(',') : [];
};

const D4ToD5Icon = (value) => {
  value = value.split('|');
  value = {
    unicode: value[0],
    type: value[2],
    weight: value[4],
  };
  return value;
};

const D4ToD5Spacing = (value) => {
  value = value.split('|');
  value = {
    top: value[0],
    right: value[1],
    bottom: value[2],
    left: value[3],
    syncHorizontal: value[4],
    syncVertical: value[5],
  };
  return value;
};

export const conversionOutline = {
    module: {
    advanced: {
        admin_label: "module.meta.adminLabel",
        background: "module.decoration.background",
        fonts: {
            filter_buttons: "filter_buttons.decoration.font",
            filter_button_active: "filter_button_active.decoration.font",
            filter_button_active_container_header_title: "filter_button_active_container_header_title.decoration.font",
            filter_button_active_container_show: "filter_button_active_container_show.decoration.font",
            filter_button_active_container_cancel: "filter_button_active_container_cancel.decoration.font",
            multi_filter_input: "multi_filter_input.decoration.font",
            multi_filter_text: "multi_filter_text.decoration.font",
            load_more: "load_more.decoration.font",
            search_bar: "search_bar.decoration.font",
            search_bar_button: "search_bar_button.decoration.font",
            empty_post_message: "empty_post_message.decoration.font",
            multi_filter_checkbox_label: "multi_filter_checkbox_label.decoration.font",
            multi_filter_acf_checkbox_text: "multi_filter_acf_checkbox_text.decoration.font",
            multi_filter_pod_checkbox_text: "multi_filter_pod_checkbox_text.decoration.font",
            multi_filter_range_label: "multi_filter_range_label.decoration.font",
            multi_filter_range_tooltip_text: "multi_filter_range_tooltip_text.decoration.font",
            multi_filter_range_min_max_text: "multi_filter_range_min_max_text.decoration.font"
        },
        borders: {
            item_outer: "item_outer.decoration.border",
            item: "item.decoration.border",
            filter_buttons: "filter_buttons.decoration.border",
            filter_button_active: "filter_button_active.decoration.border",
            filter_button_active_container_header: "filter_button_active_container_header.decoration.border",
            filter_button_active_container_footer: "filter_button_active_container_footer.decoration.border",
            filter_button_active_container_show: "filter_button_active_container_show.decoration.border",
            filter_button_active_container_cancel: "filter_button_active_container_cancel.decoration.border",
            multi_filter_container: "multi_filter_container.decoration.border",
            multi_filter_input: "multi_filter_input.decoration.border",
            multi_filter_dropdown_container: "multi_filter_dropdown_container.decoration.border",
            multi_filter_label: "multi_filter_label.decoration.border",
            multi_filter_range_label: "multi_filter_range_label.decoration.border",
            multi_filter_checkbox_field: "multi_filter_checkbox_field.decoration.border",
            load_more: "load_more.decoration.border",
            search_bar_input: "search_bar_input.decoration.border",
            search_bar_button: "search_bar_button.decoration.border"
        }
    },
    module: {
        use_current_loop: "use_current_loop.innerContent.*",
        post_type: "post_type.innerContent.*",
        posts_number: "posts_number.innerContent.*",
        post_display: "post_display.innerContent.*",
        tax_for_select: "tax_for_select.innerContent.*",
        tax_for_post: "tax_for_post.innerContent.*",
        tax_for_project: "tax_for_project.innerContent.*",
        tax_list_for_select: "tax_list_for_select.innerContent.*",
        tax_list_for_post: "tax_list_for_post.innerContent.*",
        tax_list_for_project: "tax_list_for_project.innerContent.*",
        tax_filter_field_type_post_category: "tax_filter_field_type_post_category.innerContent.*",
        tax_filter_field_type_post_post_tag: "tax_filter_field_type_post_post_tag.innerContent.*",
        tax_filter_field_type_post_post_format: "tax_filter_field_type_post_post_format.innerContent.*",
        tax_filter_field_type_project_project_category: "tax_filter_field_type_project_project_category.innerContent.*",
        tax_filter_field_type_project_project_tag: "tax_filter_field_type_project_project_tag.innerContent.*",
        post_terms_category: "post_terms_category.innerContent.*",
        post_terms_post_tag: "post_terms_post_tag.innerContent.*",
        post_terms_post_format: "post_terms_post_format.innerContent.*",
        project_terms_project_category: "project_terms_project_category.innerContent.*",
        project_terms_project_tag: "project_terms_project_tag.innerContent.*",
        multi_filter_type: "multi_filter_type.innerContent.*",
        orderby: "orderby.innerContent.*",
        offset_number: "offset_number.innerContent.*",
        multi_filter_dropdown_placeholder_prefix: "multi_filter_dropdown_placeholder_prefix.innerContent.*",
        use_search_bar: "use_search_bar.innerContent.*",
        search_bar_button_text: "search_bar_button_text.innerContent.*",
        search_bar_placeholder_text: "search_bar_placeholder_text.innerContent.*",
        use_empty_post_message: "use_empty_post_message.innerContent.*",
        empty_post_message: "empty_post_message.innerContent.*",
        use_load_more: "use_load_more.innerContent.*",
        use_load_more_text: "use_load_more_text.innerContent.*",
        all_items: "all_items.innerContent.*",
        all_items_text: "all_items_text.innerContent.*",
        use_image_as_background: "use_image_as_background.innerContent.*",
        use_background_scale: "use_background_scale.innerContent.*",
        entire_item_clickable: "entire_item_clickable.innerContent.*",
        alignment: "alignment.innerContent.*",
        layout: "layout.innerContent.*",
        column: "column.innerContent.*",
        gutter: "gutter.innerContent.*",
        equal_height: "equal_height.innerContent.*",
        filter_buttons: "filter_buttons.innerContent.*",
        filter_button_align: "filter_button_align.innerContent.*",
        filter_nav_gap: "filter_nav_gap.innerContent.*",
        filter_buttons_margin: "filter_buttons_margin.decoration.spacing.*.margin",
        filter_buttons_padding: "filter_buttons_padding.decoration.spacing.*.padding",
        filter_button_active: "filter_button_active.innerContent.*",
        filter_button_active_margin: "filter_button_active_margin.decoration.spacing.*.margin",
        filter_button_active_padding: "filter_button_active_padding.decoration.spacing.*.padding",
        filter_button_active_container_header: "filter_button_active_container_header.innerContent.*",
        filter_button_active_container_header_cls_btn_icon_color: "filter_button_active_container_header_cls_btn_icon_color.innerContent.*",
        filter_button_active_container_header_cls_btn_bg: "filter_button_active_container_header_cls_btn_bg.innerContent.*",
        filter_button_active_container_footer: "filter_button_active_container_footer.innerContent.*",
        filter_button_active_container_show: "filter_button_active_container_show.innerContent.*",
        filter_button_active_container_cancel: "filter_button_active_container_cancel.innerContent.*",
        outer_wrpper_visibility: "outer_wrpper_visibility.innerContent.*",
        inner_wrpper_visibility: "inner_wrpper_visibility.innerContent.*",
        multi_filter_container_bg: "multi_filter_container_bg.innerContent.*",
        multi_filter_input_bg: "multi_filter_input_bg.innerContent.*",
        multi_filter_label_bg: "multi_filter_label_bg.innerContent.*",
        multi_filter_placement: "multi_filter_placement.innerContent.*",
        multi_filter_item_in_row: "multi_filter_item_in_row.innerContent.*",
        multi_filter_input_align: "multi_filter_input_align.innerContent.*",
        multi_filter_container_width: "multi_filter_container_width.innerContent.*",
        multi_filter_item_align: "multi_filter_item_align.innerContent.*",
        multi_filter_item_full_width: "multi_filter_item_full_width.innerContent.*",
        use_multi_filter_label: "use_multi_filter_label.innerContent.*",
        prefix_multi_filter_label: "prefix_multi_filter_label.innerContent.*",
        multi_filter_label_position: "multi_filter_label_position.innerContent.*",
        enable_single_filter_label: "enable_single_filter_label.innerContent.*",
        single_label_text: "single_label_text.innerContent.*",
        multi_filter_input_gap: "multi_filter_input_gap.innerContent.*",
        multi_filter_autocomplete_max_height: "multi_filter_autocomplete_max_height.innerContent.*",
        multi_filter_label_min_width: "multi_filter_label_min_width.innerContent.*",
        enable_mobile_responsive: "enable_mobile_responsive.innerContent.*",
        enable_mobile_responsive_view_on_builder: "enable_mobile_responsive_view_on_builder.innerContent.*",
        multi_filter_input_gap_for_mobile: "multi_filter_input_gap_for_mobile.innerContent.*",
        multi_filter_dropdown_container_margin: "multi_filter_dropdown_container_margin.decoration.spacing.*.margin",
        multi_filter_dropdown_container_padding: "multi_filter_dropdown_container_padding.decoration.spacing.*.padding",
        multi_filter_checkbox_field_bg: "multi_filter_checkbox_field_bg.innerContent.*",
        multi_filter_checkbox_field_margin: "multi_filter_checkbox_field_margin.decoration.spacing.*.margin",
        multi_filter_checkbox_field_padding: "multi_filter_checkbox_field_padding.decoration.spacing.*.padding",
        multi_filter_checkbox_field_checkbox_item_gap: "multi_filter_checkbox_field_checkbox_item_gap.innerContent.*",
        multi_filter_checkbox_field_checkbox_item_space_left: "multi_filter_checkbox_field_checkbox_item_space_left.innerContent.*",
        multi_filter_checkbox_field_checkbox_size: "multi_filter_checkbox_field_checkbox_size.innerContent.*",
        multi_filter_checkbox_field_checkbox_text_space_left: "multi_filter_checkbox_field_checkbox_text_space_left.innerContent.*",
        multi_filter_checkbox_field_checkbox_checked_color: "multi_filter_checkbox_field_checkbox_checked_color.innerContent.*",
        multi_filter_range_bg: "multi_filter_range_bg.innerContent.*",
        multi_filter_range_active_color: "multi_filter_range_active_color.innerContent.*",
        multi_filter_range_active_border_color: "multi_filter_range_active_border_color.innerContent.*",
        multi_filter_range_tooltip_bg: "multi_filter_range_tooltip_bg.innerContent.*",
        multi_filter_range_min_max_bg: "multi_filter_range_min_max_bg.innerContent.*",
        multi_filter_range_label_min_width: "multi_filter_range_label_min_width.innerContent.*",
        multi_filter_range_label_bg: "multi_filter_range_label_bg.innerContent.*",
        search_bar_wrapper_background: "search_bar_wrapper_background.innerContent.*",
        search_bar_input_background: "search_bar_input_background.innerContent.*",
        search_bar_button_background: "search_bar_button_background.innerContent.*",
        search_input_width: "search_input_width.innerContent.*",
        search_bar_align: "search_bar_align.innerContent.*",
        use_search_bar_icon: "use_search_bar_icon.innerContent.*",
        search_bar_font_icon: "search_bar_font_icon.innerContent.*",
        search_button_icon_size: "search_button_icon_size.innerContent.*",
        search_button_icon_color: "search_button_icon_color.innerContent.*",
        search_button_icon_placement: "search_button_icon_placement.innerContent.*",
        use_only_search_bar_icon: "use_only_search_bar_icon.innerContent.*",
        load_more_align: "load_more_align.innerContent.*",
        full_width_load_more: "full_width_load_more.innerContent.*",
        use_load_more_icon: "use_load_more_icon.innerContent.*",
        load_more_font_icon: "load_more_font_icon.innerContent.*",
        load_more_icon_pos: "load_more_icon_pos.innerContent.*",
        load_more_background: "load_more_background.innerContent.*",
        load_more_margin: "load_more_margin.decoration.spacing.*.margin",
        load_more_padding: "load_more_padding.decoration.spacing.*.padding",
        item_outer_background: "item_outer_background.innerContent.*",
        item_inner_background: "item_inner_background.innerContent.*",
        wrapper_margin: "wrapper_margin.decoration.spacing.*.margin",
        wrapper_padding: "wrapper_padding.decoration.spacing.*.padding",
        item_wrapper_padding: "item_wrapper_padding.decoration.spacing.*.padding",
        item_margin: "item_margin.decoration.spacing.*.margin",
        item_padding: "item_padding.decoration.spacing.*.padding",
        search_bar_wrapper_margin: "search_bar_wrapper_margin.decoration.spacing.*.margin",
        search_bar_wrapper_padding: "search_bar_wrapper_padding.decoration.spacing.*.padding",
        search_bar_input_padding: "search_bar_input_padding.decoration.spacing.*.padding",
        search_bar_button_margin: "search_bar_button_margin.decoration.spacing.*.margin",
        search_bar_button_padding: "search_bar_button_padding.decoration.spacing.*.padding",
        search_bar_button_icon_margin: "search_bar_button_icon_margin.decoration.spacing.*.margin",
        multi_filter_container_margin: "multi_filter_container_margin.decoration.spacing.*.margin",
        multi_filter_container_padding: "multi_filter_container_padding.decoration.spacing.*.padding",
        multi_filter_input_margin: "multi_filter_input_margin.decoration.spacing.*.margin",
        multi_filter_input_padding: "multi_filter_input_padding.decoration.spacing.*.padding",
        multi_filter_label_margin: "multi_filter_label_margin.decoration.spacing.*.margin",
        multi_filter_label_padding: "multi_filter_label_padding.decoration.spacing.*.padding",
        loader_spining: "loader_spining.innerContent.*",
        loader_spinning_type: "loader_spinning_type.innerContent.*",
        loader_spinning_color: "loader_spinning_color.innerContent.*",
        loader_spinning_bg_color: "loader_spinning_bg_color.innerContent.*",
        loader_spining_size: "loader_spining_size.innerContent.*",
        loader_spinning_alignment: "loader_spinning_alignment.innerContent.*",
        loader_spinning_margin: "loader_spinning_margin.decoration.spacing.*.margin",
        loader_spining_top_position: "loader_spining_top_position.innerContent.*",
        loader_overlay: "loader_overlay.innerContent.*",
        loader_background: "loader_background.innerContent.*"
    },
    valueExpansionFunctionMap: {
        filter_buttons_margin: D4ToD5Spacing,
        filter_buttons_padding: D4ToD5Spacing,
        filter_button_active_margin: D4ToD5Spacing,
        filter_button_active_padding: D4ToD5Spacing,
        multi_filter_dropdown_container_margin: D4ToD5Spacing,
        multi_filter_dropdown_container_padding: D4ToD5Spacing,
        multi_filter_checkbox_field_margin: D4ToD5Spacing,
        multi_filter_checkbox_field_padding: D4ToD5Spacing,
        load_more_margin: D4ToD5Spacing,
        load_more_padding: D4ToD5Spacing,
        wrapper_margin: D4ToD5Spacing,
        wrapper_padding: D4ToD5Spacing,
        item_wrapper_padding: D4ToD5Spacing,
        item_margin: D4ToD5Spacing,
        item_padding: D4ToD5Spacing,
        search_bar_wrapper_margin: D4ToD5Spacing,
        search_bar_wrapper_padding: D4ToD5Spacing,
        search_bar_input_padding: D4ToD5Spacing,
        search_bar_button_margin: D4ToD5Spacing,
        search_bar_button_padding: D4ToD5Spacing,
        search_bar_button_icon_margin: D4ToD5Spacing,
        multi_filter_container_margin: D4ToD5Spacing,
        multi_filter_container_padding: D4ToD5Spacing,
        multi_filter_input_margin: D4ToD5Spacing,
        multi_filter_input_padding: D4ToD5Spacing,
        multi_filter_label_margin: D4ToD5Spacing,
        multi_filter_label_padding: D4ToD5Spacing,
        loader_spinning_margin: D4ToD5Spacing
    }
}
};
