const convertInlineValue = (value) => {
  return _.isString(value) ? value.split(',') : [];
};

const D4ToD5Icon = (value) => {
  value = value.split('|');
  value = {
    unicode: value[0],
    type: value[2],
    weight: value[4],
  };
  return value;
};

const D4ToD5Spacing = (value) => {
  value = value.split('|');
  value = {
    top: value[0],
    right: value[1],
    bottom: value[2],
    left: value[3],
    syncHorizontal: value[4],
    syncVertical: value[5],
  };
  return value;
};

export const conversionOutline = {
    module: {
    advanced: {
        admin_label: "module.meta.adminLabel",
        background: "module.decoration.background",
        fonts: {
            line_top_txt: "line_top_txt.decoration.font",
            line_bottom_txt: "line_bottom_txt.decoration.font",
            title: "title.decoration.font",
            subtitle: "subtitle.decoration.font",
            design_content_text: "design_content_text.decoration.font",
            content_button: "content_button.decoration.font",
            date_title: "date_title.decoration.font",
            date_subtitle: "date_subtitle.decoration.font"
        },
        borders: {
            default: "module.decoration.border",
            item_wrapper_border: "item_wrapper_border.decoration.border",
            title_border: "title_border.decoration.border",
            subtitle_border: "subtitle_border.decoration.border",
            content_text_wrapper_border: "content_text_wrapper_border.decoration.border",
            content_media_border: "content_media_border.decoration.border",
            content_button_border: "content_button_border.decoration.border",
            line_top_border: "line_top_border.decoration.border",
            line_bottom_border: "line_bottom_border.decoration.border",
            marker_wrapper_border: "marker_wrapper_border.decoration.border",
            date_wrapper_border: "date_wrapper_border.decoration.border"
        },
        box_shadow: {
            default: "module.decoration.boxShadow"
        },
        filters: {
            default: "module.decoration.filters"
        },
        margin_padding: "module.decoration.spacing"
    },
    module: {
        layout_type: "layout_type.innerContent.*",
        layout_type_mobile: "layout_type_mobile.innerContent.*",
        module_area_width: "module_area_width.innerContent.*",
        blurb_area_width: "blurb_area_width.innerContent.*",
        date_area_width: "date_area_width.innerContent.*",
        disable_date: "disable_date.innerContent.*",
        item_horizontal_alignment: "item_horizontal_alignment.innerContent.*",
        item_horizontal_gap: "item_horizontal_gap.innerContent.*",
        item_vertical_alignment: "item_vertical_alignment.innerContent.*",
        item_vertical_gap: "item_vertical_gap.innerContent.*",
        enable_date_in_blurb: "enable_date_in_blurb.innerContent.*",
        date_horizontal_alignment: "date_horizontal_alignment.innerContent.*",
        disable_date_mobile: "disable_date_mobile.innerContent.*",
        arrow_marker_vertical_align: "arrow_marker_vertical_align.innerContent.*",
        marker_postion_mobile: "marker_postion_mobile.innerContent.*",
        line_top_bg: "line_top_bg.innerContent.*",
        line_bottom_bg: "line_bottom_bg.innerContent.*",
        line_color: "line_color.innerContent.*",
        line_width: "line_width.innerContent.*",
        line_start_from: "line_start_from.innerContent.*",
        enable_line_top_marker: "enable_line_top_marker.innerContent.*",
        line_top_marker_type: "line_top_marker_type.innerContent.*",
        line_top_icon: "line_top_icon.innerContent.*",
        line_top_icon_color: "line_top_icon_color.innerContent.*",
        line_top_icon_size: "line_top_icon_size.innerContent.*",
        line_top_image: "line_top_image.innerContent.*",
        line_top_img_alt_txt: "line_top_img_alt_txt.innerContent.*",
        line_top_img_width: "line_top_img_width.innerContent.*",
        line_top_txt: "line_top_txt.innerContent.*",
        line_top_marker_vertical_position: "line_top_marker_vertical_position.innerContent.*",
        enable_line_bottom_marker: "enable_line_bottom_marker.innerContent.*",
        line_bottom_marker_type: "line_bottom_marker_type.innerContent.*",
        line_bottom_icon: "line_bottom_icon.innerContent.*",
        line_bottom_icon_color: "line_bottom_icon_color.innerContent.*",
        line_bottom_icon_size: "line_bottom_icon_size.innerContent.*",
        line_bottom_image: "line_bottom_image.innerContent.*",
        line_bottom_img_alt_txt: "line_bottom_img_alt_txt.innerContent.*",
        line_bottom_img_width: "line_bottom_img_width.innerContent.*",
        line_bottom_txt: "line_bottom_txt.innerContent.*",
        line_bottom_marker_vertical_position: "line_bottom_marker_vertical_position.innerContent.*",
        enable_arrow: "enable_arrow.innerContent.*",
        arrow_type: "arrow_type.innerContent.*",
        arrow_icon: "arrow_icon.innerContent.*",
        arrow_line_type: "arrow_line_type.innerContent.*",
        arrow_thick: "arrow_thick.innerContent.*",
        arrow_size: "arrow_size.innerContent.*",
        arrow_color: "arrow_color.innerContent.*",
        arrow_vertical_alignment: "arrow_vertical_alignment.innerContent.*",
        arrow_vertical_position: "arrow_vertical_position.innerContent.*",
        arrow_horizontal_position: "arrow_horizontal_position.innerContent.*",
        reverse_arrow: "reverse_arrow.innerContent.*",
        disable_arrow_mobile: "disable_arrow_mobile.innerContent.*",
        enable_date_arrow: "enable_date_arrow.innerContent.*",
        date_arrow_type: "date_arrow_type.innerContent.*",
        date_arrow_icon: "date_arrow_icon.innerContent.*",
        date_arrow_line_type: "date_arrow_line_type.innerContent.*",
        date_arrow_thick: "date_arrow_thick.innerContent.*",
        date_arrow_size: "date_arrow_size.innerContent.*",
        date_arrow_color: "date_arrow_color.innerContent.*",
        date_arrow_vertical_align: "date_arrow_vertical_align.innerContent.*",
        date_arrow_vertical_position: "date_arrow_vertical_position.innerContent.*",
        date_arrow_horizontal_position: "date_arrow_horizontal_position.innerContent.*",
        reverse_date_arrow: "reverse_date_arrow.innerContent.*",
        disable_date_arrow_mobile: "disable_date_arrow_mobile.innerContent.*",
        content_button_bg: "content_button_bg.innerContent.*",
        button_icon_color: "button_icon_color.innerContent.*",
        button_icon_size: "button_icon_size.innerContent.*",
        timeline_button_margin: "timeline_button_margin.decoration.spacing.*.margin",
        timeline_button_padding: "timeline_button_padding.decoration.spacing.*.padding",
        enable_item_animation: "enable_item_animation.innerContent.*",
        tmln_animation: "tmln_animation.innerContent.*",
        enable_scroll_line: "enable_scroll_line.innerContent.*",
        scroll_line_color: "scroll_line_color.innerContent.*",
        enable_marker_animation: "enable_marker_animation.innerContent.*",
        active_marker_bg: "active_marker_bg.innerContent.*",
        active_marker_color: "active_marker_color.innerContent.*",
        order_enable: "order_enable.innerContent.*",
        date_order: "date_order.innerContent.*",
        title_order: "title_order.innerContent.*",
        sub_title_order: "sub_title_order.innerContent.*",
        media_order: "media_order.innerContent.*",
        content_order: "content_order.innerContent.*",
        button_order: "button_order.innerContent.*",
        item_wrapper_bg: "item_wrapper_bg.innerContent.*",
        title_bg: "title_bg.innerContent.*",
        subtitle_bg: "subtitle_bg.innerContent.*",
        content_text_bg: "content_text_bg.innerContent.*",
        content_media_bg: "content_media_bg.innerContent.*",
        marker_bg: "marker_bg.innerContent.*",
        marker_width: "marker_width.innerContent.*",
        marker_height: "marker_height.innerContent.*",
        marker_icon_color: "marker_icon_color.innerContent.*",
        marker_icon_size: "marker_icon_size.innerContent.*",
        date_wrapper_bg: "date_wrapper_bg.innerContent.*",
        timeline_title_margin: "timeline_title_margin.decoration.spacing.*.margin",
        timeline_title_padding: "timeline_title_padding.decoration.spacing.*.padding",
        timeline_subtitle_margin: "timeline_subtitle_margin.decoration.spacing.*.margin",
        timeline_subtitle_padding: "timeline_subtitle_padding.decoration.spacing.*.padding",
        item_wrapper_margin: "item_wrapper_margin.decoration.spacing.*.margin",
        item_wrapper_padding: "item_wrapper_padding.decoration.spacing.*.padding",
        timeline_content_margin: "timeline_content_margin.decoration.spacing.*.margin",
        timeline_content_padding: "timeline_content_padding.decoration.spacing.*.padding",
        timeline_media_item_margin: "timeline_media_item_margin.decoration.spacing.*.margin",
        timeline_media_item_padding: "timeline_media_item_padding.decoration.spacing.*.padding",
        date_wrapper_margin: "date_wrapper_margin.decoration.spacing.*.margin",
        date_wrapper_padding: "date_wrapper_padding.decoration.spacing.*.padding",
        date_title_margin: "date_title_margin.decoration.spacing.*.margin",
        date_subtitle_margin: "date_subtitle_margin.decoration.spacing.*.margin",
        line_top_wrapper_margin: "line_top_wrapper_margin.decoration.spacing.*.margin",
        line_top_wrapper_padding: "line_top_wrapper_padding.decoration.spacing.*.padding",
        line_bottom_wrapper_margin: "line_bottom_wrapper_margin.decoration.spacing.*.margin",
        line_bottom_wrapper_padding: "line_bottom_wrapper_padding.decoration.spacing.*.padding"
    },
    valueExpansionFunctionMap: {
        timeline_button_margin: D4ToD5Spacing,
        timeline_button_padding: D4ToD5Spacing,
        timeline_title_margin: D4ToD5Spacing,
        timeline_title_padding: D4ToD5Spacing,
        timeline_subtitle_margin: D4ToD5Spacing,
        timeline_subtitle_padding: D4ToD5Spacing,
        item_wrapper_margin: D4ToD5Spacing,
        item_wrapper_padding: D4ToD5Spacing,
        timeline_content_margin: D4ToD5Spacing,
        timeline_content_padding: D4ToD5Spacing,
        timeline_media_item_margin: D4ToD5Spacing,
        timeline_media_item_padding: D4ToD5Spacing,
        date_wrapper_margin: D4ToD5Spacing,
        date_wrapper_padding: D4ToD5Spacing,
        date_title_margin: D4ToD5Spacing,
        date_subtitle_margin: D4ToD5Spacing,
        line_top_wrapper_margin: D4ToD5Spacing,
        line_top_wrapper_padding: D4ToD5Spacing,
        line_bottom_wrapper_margin: D4ToD5Spacing,
        line_bottom_wrapper_padding: D4ToD5Spacing
    }
}
};
