import {D4ToD5Background, D4ToD5Spacing} from "../../healper/conversion";

export const conversionOutline = {
    advanced: {
        admin_label: "module.meta.adminLabel",
        background: "module.decoration.background",
        fonts: {
            name: "name.decoration.font",
            role: "role.decoration.font",
            description: "description.decoration.font",
            content: "content.decoration.font"
        },
        borders: {
            default: "module.decoration.border",
            name_border: "name.decoration.border",
            role_border: "role.decoration.border",
            description_border: "description.decoration.border",
            content_border: "content.decoration.border",
            photo_wrapper_border: "image_wrapper.decoration.border",
            photo_border: "image.decoration.border",
            social_container_border: "social_container_border.decoration.border",
            social_icon_border: "social_icon_border.decoration.border"
        },
        box_shadow: {
            default: "module.decoration.boxShadow",
            content_shadow: "content.decoration.boxShadow",
            image_shadow: "image.decoration.boxShadow",
            image_wrapper_shadow: "image_wrapper.decoration.boxShadow",
            social_icon_shadow: "social_icon_shadow.decoration.boxShadow",
        },
    },
    module: {
        style_type: "style_type.innerContent.*",
        ap_photo: "ap_photo.innerContent.*",
        photo_alt_text: "photo_alt_text.innerContent.*",
        enable_alternative_photo: "enable_alternative_photo.innerContent.*",
        ap_alternative_photo: "ap_alternative_photo.innerContent.*",
        alternative_photo_alt_text: "alternative_photo_alt_text.innerContent.*",
        enable_icon_on_overlay: "enable_icon_on_overlay.innerContent.*",
        anm_content_padding: "anm_content_padding.innerContent.*",
        content_position: "content_position.innerContent.*",
        always_show_icon: "always_show_icon.innerContent.*",
        icon_reveal_caption: "icon_reveal_caption.innerContent.*",
        // image_wrapper_background: "image_wrapper.innerContent.*",
        image_wrapper_max_width: "image_wrapper.innerContent.*",
        image_wrapper_zindex: "image_wrapper.decoration.zIndex.*",
        image_alignment: "image_alignment.innerContent.*",
        image_force_to_fullwidth: "image_force_to_fullwidth.innerContent.*",
        image_scale_type: "image_scale_type.innerContent.*",
        image_scale_value: "image_scale_value.innerContent.*",
        overlay: "overlay.innerContent.*",
        // ekip_overlay_background: "ekip_overlay_background.innerContent.*",
        // default_overlay_background: "default_overlay_background.innerContent.*",
        anim_direction: "anim_direction.innerContent.*",
        overlay_transition_transition_duration: "overlay_transition_transition_duration.innerContent.*",
        overlay_transition_transition_delay: "overlay_transition_transition_delay.innerContent.*",
        overlay_transition_transition_curve: "overlay_transition_transition_curve.innerContent.*",
        border_anim: "border_anim.innerContent.*",
        anm_border_color: "anm_border_color.innerContent.*",
        anm_border_width: "anm_border_width.innerContent.*",
        anm_border_margin: "anm_border_margin.innerContent.*",
        border_anm_style: "border_anm_style.innerContent.*",
        ap_name: "name.innerContent.*",
        ap_role: "ap_role.innerContent.*",
        ap_description: "ap_description.innerContent.*",
        ap_name_tag: "ap_name_tag.innerContent.*",
        ap_role_tag: "ap_role_tag.innerContent.*",
        ...D4ToD5Background('content_background','content'),
        ...D4ToD5Background('description_background','description'),
        content_zindex: "content_zindex.innerContent.*",
        ap_facebook: "ap_facebook.innerContent.*",
        ap_twitter: "ap_twitter.innerContent.*",
        ap_linkedin: "ap_linkedin.innerContent.*",
        ap_instagram: "ap_instagram.innerContent.*",
        ap_pinterest: "ap_pinterest.innerContent.*",
        ap_email: "ap_email.innerContent.*",
        ap_phone: "ap_phone.innerContent.*",
        social_section_align: "social_section_align.innerContent.*",
        make_vertical_icon: "make_vertical_icon.innerContent.*",
        make_full_with_icon: "make_full_with_icon.innerContent.*",
        icon_size: "icon.decoration.font.font.*.size",
        icon_color: "icon_color.decoration.font.font.*.color",
        ...D4ToD5Background('icon_background','icon'),
        ...D4ToD5Background('name_background', 'name'),
        ...D4ToD5Background('role_background', 'role'),
        ...D4ToD5Background('social_wrapper_background', 'social_wrapper'),
        ...D4ToD5Background('facebook_background', 'facebook'),
        ...D4ToD5Background('twitter_background', 'twitter'),
        ...D4ToD5Background('linkedin_background', 'linkedin'),
        ...D4ToD5Background('instagram_background', 'instagram'),
        ...D4ToD5Background('pinterest_background', 'pinterest'),
        ...D4ToD5Background('email_background', 'email'),
        ...D4ToD5Background('phone_background', 'phone'),
        ...D4ToD5Background('ekip_overlay_background', 'ekip_overlay_background'),
        ...D4ToD5Background('default_overlay_background', 'default_overlay_background'),
        ...D4ToD5Background('image_wrapper_background', 'image_wrapper'),
        facebook_icon_color: "facebook.decoration.font.font.*.color",
        twitter_icon_color: "twitter.decoration.font.font.*.color",
        linkedin_icon_color: "linkedin.decoration.font.font.*.color",
        instagram_icon_color: "instagram.decoration.font.font.*.color",
        pinterest_icon_color: "pinterest.decoration.font.font.*.color",
        email_icon_color: "email.decoration.font.font.*.color",
        phone_icon_color: "phone.decoration.font.font.*.color",
        module_wrapper_margin: "module_wrapper.decoration.spacing.*.margin",
        module_wrapper_padding: "module_wrapper.decoration.spacing.*.padding",
        image_wrapper_margin: "image_wrapper.decoration.spacing.*.margin",
        image_wrapper_padding: "image_wrapper.decoration.spacing.*.padding",
        content_margin: "content.decoration.spacing.*.margin",
        content_padding: "content.decoration.spacing.*.padding",
        details_wrapper_margin: "details_wrapper.decoration.spacing.*.margin",
        details_wrapper_padding: "details_wrapper.decoration.spacing.*.padding",
        social_wrapper_margin: "social_wrapper.decoration.spacing.*.margin",
        social_wrapper_padding: "social_wrapper.decoration.spacing.*.padding",
        name_margin: "name.decoration.spacing.*.margin",
        name_padding: "name.decoration.spacing.*.padding",
        role_margin: "role.decoration.spacing.*.margin",
        role_padding: "role.decoration.spacing.*.padding",
        description_margin: "description.decoration.spacing.*.margin",
        description_padding: "description.decoration.spacing.*.padding",
        image_margin: "image.decoration.spacing.*.margin",
        image_padding: "image.decoration.spacing.*.padding",
        social_margin: "social.decoration.spacing.*.margin",
        social_padding: "social.decoration.spacing.*.padding",
        first_social_margin: "first_social.decoration.spacing.*.margin",
        last_social_margin: "last_social.decoration.spacing.*.margin"
    },
    valueExpansionFunctionMap: {
        module_wrapper_margin: D4ToD5Spacing,
        module_wrapper_padding: D4ToD5Spacing,
        image_wrapper_margin: D4ToD5Spacing,
        image_wrapper_padding: D4ToD5Spacing,
        content_margin: D4ToD5Spacing,
        content_padding: D4ToD5Spacing,
        details_wrapper_margin: D4ToD5Spacing,
        details_wrapper_padding: D4ToD5Spacing,
        social_wrapper_margin: D4ToD5Spacing,
        social_wrapper_padding: D4ToD5Spacing,
        name_margin: D4ToD5Spacing,
        name_padding: D4ToD5Spacing,
        role_margin: D4ToD5Spacing,
        role_padding: D4ToD5Spacing,
        description_margin: D4ToD5Spacing,
        description_padding: D4ToD5Spacing,
        image_margin: D4ToD5Spacing,
        image_padding: D4ToD5Spacing,
        social_margin: D4ToD5Spacing,
        social_padding: D4ToD5Spacing,
        first_social_margin: D4ToD5Spacing,
        last_social_margin: D4ToD5Spacing,
    }
};
