const convertInlineValue = (value) => {
  return _.isString(value) ? value.split(',') : [];
};

const convertIcon = (value) => {
  value = value.split('|');
  value = {
    unicode: value[0],
    type: value[2],
    weight: value[4],
  };
  return value;
};

const convertSpacing = (value) => {
  value = value.split('|');
  value = {
    top: value[0],
    right: value[1],
    bottom: value[2],
    left: value[3],
    syncHorizontal: value[4],
    syncVertical: value[5],
  };
  return value;
};

export const conversionOutline = {
    module: {
    advanced: {
        admin_label: "module.meta.adminLabel",
        background: "module.decoration.background",
        fonts: {
            form_title: "form_title.decoration.font",
            form_description: "form_description.decoration.font",
            form_heading_notice: "form_heading_notice.decoration.font",
            label: "label.decoration.font",
            "sub-label": "sub-label.decoration.font",
            description: "description.decoration.font",
            warning_text: "warning_text.decoration.font",
            input: "input.decoration.font",
            select: "select.decoration.font",
            textarea: "textarea.decoration.font",
            checkbox: "checkbox.decoration.font",
            radio: "radio.decoration.font",
            button: "button.decoration.font",
            section_title: "section_title.decoration.font",
            section_description: "section_description.decoration.font",
            progress_title: "progress_title.decoration.font",
            progress_step_name: "progress_step_name.decoration.font",
            confirm: "confirm.decoration.font",
            consent_label: "consent_label.decoration.font",
            consent_sublabel: "consent_sublabel.decoration.font",
            consent_description: "consent_description.decoration.font",
            required_text: "required_text.decoration.font",
            error_box_global: "error_box_global.decoration.font",
            error_box: "error_box.decoration.font",
            time: "time.decoration.font"
        },
        borders: {
            heading: "heading.decoration.border",
            input: "input.decoration.border",
            select: "select.decoration.border",
            textarea: "textarea.decoration.border",
            button: "button.decoration.border",
            section: "section.decoration.border",
            confirm: "confirm.decoration.border",
            error_box_global: "error_box_global.decoration.border",
            error_box: "error_box.decoration.border",
            time: "time.decoration.border"
        },
        filters: {
            default: "module.decoration.filters"
        }
    },
    module: {
        gravity_forms: "gravity_forms.innerContent.*",
        show_title: "show_title.innerContent.*",
        show_description: "show_description.innerContent.*",
        use_ajax: "use_ajax.innerContent.*",
        tabindex: "tabindex.innerContent.*",
        __gravityFormShortcode: "__gravityFormShortcode.innerContent.*",
        heading_background: "heading_background.innerContent.*",
        heading_margin: "heading_margin.decoration.spacing.*.margin",
        heading_padding: "heading_padding.decoration.spacing.*.padding",
        input_background: "input_background.innerContent.*",
        input_margin: "input_margin.decoration.spacing.*.margin",
        input_padding: "input_padding.decoration.spacing.*.padding",
        input_placeholder_color: "input_placeholder_color.innerContent.*",
        select_background: "select_background.innerContent.*",
        select_margin: "select_margin.decoration.spacing.*.margin",
        select_padding: "select_padding.decoration.spacing.*.padding",
        textarea_background: "textarea_background.innerContent.*",
        textarea_margin: "textarea_margin.decoration.spacing.*.margin",
        textarea_padding: "textarea_padding.decoration.spacing.*.padding",
        textarea_placeholder_color: "textarea_placeholder_color.innerContent.*",
        checkbox_gap: "checkbox_gap.innerContent.*",
        checkbox_background: "checkbox_background.innerContent.*",
        checkbox_tickcolor: "checkbox_tickcolor.innerContent.*",
        checkbox_bordercolor: "checkbox_bordercolor.innerContent.*",
        checkbox_size: "checkbox_size.innerContent.*",
        checkbox_bordersize: "checkbox_bordersize.innerContent.*",
        radio_gap: "radio_gap.innerContent.*",
        radio_box: "radio_box.innerContent.*",
        radio_background: "radio_background.innerContent.*",
        radio_dotcolor: "radio_dotcolor.innerContent.*",
        radio_bordercolor: "radio_bordercolor.innerContent.*",
        radio_size: "radio_size.innerContent.*",
        radio_bordersize: "radio_bordersize.innerContent.*",
        consent_checkbox_background: "consent_checkbox_background.innerContent.*",
        consent_checkbox_tickcolor: "consent_checkbox_tickcolor.innerContent.*",
        consent_checkbox_bordercolor: "consent_checkbox_bordercolor.innerContent.*",
        consent_checkbox_size: "consent_checkbox_size.innerContent.*",
        consent_checkbox_bordersize: "consent_checkbox_bordersize.innerContent.*",
        consent_description_background: "consent_description_background.innerContent.*",
        consent_description_bordercolor: "consent_description_bordercolor.innerContent.*",
        button_align: "button_align.innerContent.*",
        button_full_width: "button_full_width.innerContent.*",
        button_background: "button_background.innerContent.*",
        btn_icon_color: "btn_icon_color.innerContent.*",
        button_margin: "button_margin.decoration.spacing.*.margin",
        button_padding: "button_padding.decoration.spacing.*.padding",
        section_background: "section_background.innerContent.*",
        section_margin: "section_margin.decoration.spacing.*.margin",
        section_padding: "section_padding.decoration.spacing.*.padding",
        section_title_padding: "section_title_padding.decoration.spacing.*.padding",
        section_description_padding: "section_description_padding.decoration.spacing.*.padding",
        progress_margin: "progress_margin.decoration.spacing.*.margin",
        progress_padding: "progress_padding.decoration.spacing.*.padding",
        progress_background: "progress_background.innerContent.*",
        progress_color: "progress_color.innerContent.*",
        steps_align: "steps_align.innerContent.*",
        step_background: "step_background.innerContent.*",
        step_color: "step_color.innerContent.*",
        step_bordercolor: "step_bordercolor.innerContent.*",
        active_step_background: "active_step_background.innerContent.*",
        active_step_color: "active_step_color.innerContent.*",
        active_step_bordercolor: "active_step_bordercolor.innerContent.*",
        complete_step_background: "complete_step_background.innerContent.*",
        complete_step_color: "complete_step_color.innerContent.*",
        step_bottom_bordercolor: "step_bottom_bordercolor.innerContent.*",
        confirm_background: "confirm_background.innerContent.*",
        confirm_margin: "confirm_margin.decoration.spacing.*.margin",
        confirm_padding: "confirm_padding.decoration.spacing.*.padding",
        input_focus_background: "input_focus_background.innerContent.*",
        input_focus_border_color: "input_focus_border_color.innerContent.*",
        input_focus_text_color: "input_focus_text_color.innerContent.*",
        select_focus_background: "select_focus_background.innerContent.*",
        select_focus_border_color: "select_focus_border_color.innerContent.*",
        select_focus_text_color: "select_focus_text_color.innerContent.*",
        textarea_focus_background: "textarea_focus_background.innerContent.*",
        textarea_focus_border_color: "textarea_focus_border_color.innerContent.*",
        textarea_focus_text_color: "textarea_focus_text_color.innerContent.*",
        error_box_global_background: "error_box_global_background.innerContent.*",
        error_box_background: "error_box_background.innerContent.*",
        error_box_global_margin: "error_box_global_margin.decoration.spacing.*.margin",
        error_box_global_padding: "error_box_global_padding.decoration.spacing.*.padding",
        error_box_margin: "error_box_margin.decoration.spacing.*.margin",
        error_box_padding: "error_box_padding.decoration.spacing.*.padding",
        time_background: "time_background.innerContent.*",
        time_input_margin: "time_input_margin.decoration.spacing.*.margin",
        time_input_padding: "time_input_padding.decoration.spacing.*.padding",
        time_select_margin: "time_select_margin.decoration.spacing.*.margin",
        time_select_padding: "time_select_padding.decoration.spacing.*.padding",
        time_input_placeholder: "time_input_placeholder.innerContent.*",
        time_colon: "time_colon.innerContent.*"
    },
    valueExpansionFunctionMap: {
        heading_margin: convertSpacing,
        heading_padding: convertSpacing,
        input_margin: convertSpacing,
        input_padding: convertSpacing,
        select_margin: convertSpacing,
        select_padding: convertSpacing,
        textarea_margin: convertSpacing,
        textarea_padding: convertSpacing,
        button_margin: convertSpacing,
        button_padding: convertSpacing,
        section_margin: convertSpacing,
        section_padding: convertSpacing,
        section_title_padding: convertSpacing,
        section_description_padding: convertSpacing,
        progress_margin: convertSpacing,
        progress_padding: convertSpacing,
        confirm_margin: convertSpacing,
        confirm_padding: convertSpacing,
        error_box_global_margin: convertSpacing,
        error_box_global_padding: convertSpacing,
        error_box_margin: convertSpacing,
        error_box_padding: convertSpacing,
        time_input_margin: convertSpacing,
        time_input_padding: convertSpacing,
        time_select_margin: convertSpacing,
        time_select_padding: convertSpacing
    }
}
};
